language: php
php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  fast_finish: true

branches:
  only:
    - master

before_script:
  - php composer.phar install --dev --no-interaction --prefer-source

script:
  - vendor/bin/phpunit
